import { Urbanist, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Chatbot from "@/components/Chatbot";
import QuickAccessBar from "@/components/QuickAccessBar";
import { HomeDataProvider } from "@/context/HomeDataContext";
import connectDB from "@/config/db";
import NavbarModel from "@/models/Navbar";
import FooterModel from "@/models/Footer";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
  weight: ["400", "500", "600", "700"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Weekend UX",
  description: "Generated by create next app",
};

// Prefetch Navbar and Footer data on the server during SSR to drop HTTP overhead
async function getLayoutInitialData() {
  try {
       await connectDB();
       const [navbarDoc, footerGlobalDoc, footerColumnsDocs] = await Promise.all([
            NavbarModel.findOne().lean(),
            FooterModel.findOne({ isGlobal: true }).lean(),
            FooterModel.find({ isGlobal: { $ne: true } }).sort({ order: 1 }).lean()
       ]);
       return {
            navbarData: navbarDoc ? JSON.parse(JSON.stringify(navbarDoc)) : null,
            footerGlobalData: footerGlobalDoc ? JSON.parse(JSON.stringify(footerGlobalDoc)) : null,
            footerColumnsData: footerColumnsDocs ? JSON.parse(JSON.stringify(footerColumnsDocs)) : null
       };
  } catch (e) {
       console.error("Failed to prefetch layout data on server:", e);
       return null;
  }
}

export default async function RootLayout({ children }) {
  const initialData = await getLayoutInitialData();

  return (
    <html
      lang="en"
      className={` ${playfair.variable} ${urbanist.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HomeDataProvider initialData={initialData}>
          <Navbar />
          <main className="flex-grow">
               {children}
          </main>
          <Chatbot />
          <QuickAccessBar />
          <Footer />
        </HomeDataProvider>
      </body>
    </html>
  );
}

