import { Urbanist, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import QuickAccessBar from "@/components/QuickAccessBar";
import { HomeDataProvider } from "@/context/HomeDataContext";

// Database imports for server-side pre-fetching
import connectDB from "@/config/db";
import Home from "@/models/Home";
import Faq from "@/models/Faq";
import Courses from "@/models/Courses";
import NavbarModel from "@/models/Navbar";
import FooterModel from "@/models/Footer";
import Testimonial from "@/models/Testimonial";
import Blog from "@/models/Blog";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Weekend UX",
  description: "Generated by create next app",
};

// Helper function to pre-fetch and serialize context data on the server
async function getInitialData() {
  try {
    await connectDB();
    const [
      homeDoc,
      faqDoc,
      coursesDoc,
      navbarDoc,
      footerGlobalDoc,
      footerColumnsDocs,
      testimonialsDocs,
      blogsDoc
    ] = await Promise.all([
      Home.findOne().lean(),
      Faq.findOne({ pageSlug: "home" }).lean(),
      Courses.findOne().lean(),
      NavbarModel.findOne().lean(),
      FooterModel.findOne({ isGlobal: true }).lean(),
      FooterModel.find({ isGlobal: { $ne: true } }).sort({ order: 1 }).lean(),
      Testimonial.find().sort({ createdAt: -1 }).lean(),
      Blog.findOne().lean()
    ]);

    return JSON.parse(JSON.stringify({
      homeData: homeDoc,
      faqData: faqDoc,
      coursesData: coursesDoc,
      navbarData: navbarDoc,
      footerGlobalData: footerGlobalDoc,
      footerColumnsData: footerColumnsDocs,
      testimonialsData: testimonialsDocs,
      blogsData: blogsDoc
    }));
  } catch (error) {
    console.error("Failed to pre-fetch initial data on server:", error);
    return null;
  }
}

export default async function RootLayout({ children }) {
  const initialData = await getInitialData();

  return (
    <html
      lang="en"
      className={` ${playfair.variable} ${urbanist.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HomeDataProvider initialData={initialData}>
          <Navbar />
          <main className="flex-grow">
               {children}
          </main>
          <QuickAccessBar />
          <Footer />
        </HomeDataProvider>
      </body>
    </html>
  );
}

