import { Urbanist, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Chatbot from "@/components/Chatbot";
import QuickAccessBar from "@/components/QuickAccessBar";
import { HomeDataProvider } from "@/context/HomeDataContext";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
  weight: ["400", "500", "600", "700"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Weekend UX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${playfair.variable} ${urbanist.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HomeDataProvider>
          <Navbar />
          <main className="flex-grow">
               {children}
          </main>
          <Chatbot />
          <QuickAccessBar />
          <Footer />
        </HomeDataProvider>
      </body>
    </html>
  );
}

