name: Deploy Next.js to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [admin_content_update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: .
        run: |
          npm install

      - name: Build static site
        working-directory: .
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          npm run build

      - name: Check export folder
        run: |
          if [ -d "out" ]; then echo "OUT_EXISTS=true"; else echo "OUT_EXISTS=false"; fi
          ls -la out || true

      - name: Upload to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/
          state-name: .ftp-deploy-sync-state.json
          dry-run: false
